{% set version = "5.0.1" %}

package:
  name: tornado
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/tornado/tornado-{{ version }}.tar.gz
  sha256: 3e9a2333362d3dad7876d902595b64aea1a2f91d0df13191ea1f8bca5a447771

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - futures              # [py<32]
    - singledispatch       # [py<34]
    - backports_abc >=0.4  # [py<35]

test:
  imports:
    - tornado
    - tornado.platform
    - tornado.test
    - tornado.gen
    - tornado.netutil

about:
  home: http://www.tornadoweb.org/
  license: Apache 2.0
  summary: 'Tornado is a Python web framework and asynchronous networking library, originally developed at FriendFeed.'

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
